name: Step 4, Copilot Comments

# This step triggers after push to comments.js
# This workflow updates from step 4 to completion.
on:
  workflow_dispatch:
  push:
    paths:
      - "comments.js"
    branches:
      - main

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_copilot_comment:
    name: On Copilot Comment Usage
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The current step is 4
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 4 }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Verify the learner added comments
      - name: Check comments
        uses: skills/action-check-file@v1
        with:
          file: "comments.js"
          search: "// Function to calculate"

      # Update to the next step
      - name: Update to final step
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: X
